# Generated by Django 5.1.4 on 2025-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('scraper_datum_id', models.IntegerField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('box_cord', models.TextField(blank=True, null=True)),
                ('textfarben', models.CharField(blank=True, max_length=30, null=True)),
                ('font_size', models.FloatField(blank=True, null=True)),
                ('hintergrundfarben', models.CharField(blank=True, max_length=30, null=True)),
                ('textstimmung', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
