services:
  django:
    build: ./django/
    restart: on-failure
    volumes:
      - ./data/images:/app/images
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    ports:
      - "8000:8000"
    networks:
      - ca-network
    depends_on:
      - db
      - tesseract

  db:
    image: postgres:16
    restart: on-failure
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - ca-network

  tesseract:
    build: ./llm/tesseract/tesseract-server-master #tesseract-ocr-5.5.0-r0
    restart: on-failure
    ports:
      - "8884:8884"
    networks:
      - ca-network

networks:
  ca-network:
    driver: bridge
