# Generated by Django 5.1.4 on 2025-01-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyocr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRProcess',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_image_path', models.TextField()),
                ('annotated_image_path', models.TextField(blank=True, null=True)),
                ('recognized_text', models.TextField()),
                ('avg_confidence', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=100)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
