# Generated by Django 5.1.4 on 2025-01-20 11:17

import datetime
import django.db.models.deletion
import scraper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_in_batch', models.SmallIntegerField()),
                ('has_next_page', models.BooleanField()),
                ('end_cursor', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('extensions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_id', models.BigIntegerField()),
                ('start_cursor', models.TextField(blank=True, null=True)),
                ('scrape_max_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('scrape_max_notes', models.IntegerField()),
                ('scrape_max_batches', models.SmallIntegerField()),
                ('scrape_notes_per_batch', models.SmallIntegerField()),
                ('status', models.CharField(max_length=100, validators=[scraper.models.validate_run_status])),
                ('total_data_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('shortcode', models.CharField(max_length=100)),
                ('comment_count', models.IntegerField()),
                ('comments_disabled', models.BooleanField()),
                ('taken_at_timestamp', models.IntegerField()),
                ('display_height', models.IntegerField()),
                ('display_width', models.IntegerField()),
                ('display_url', models.TextField()),
                ('likes_count', models.IntegerField()),
                ('owner_id', models.BigIntegerField()),
                ('thumbnail_src', models.TextField()),
                ('thumbnail_resources', models.TextField()),
                ('is_video', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scrape_batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapebatch')),
                ('scraper_run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.scraperrun')),
            ],
        ),
        migrations.AddField(
            model_name='scrapebatch',
            name='scraper_run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.scraperrun'),
        ),
    ]
