# Generated by Django 5.1.4 on 2025-01-12 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.SmallIntegerField()),
                ('end_cursor', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_iid', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scrape_batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapebatch')),
            ],
        ),
        migrations.AddField(
            model_name='scrapebatch',
            name='scraper_run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.scraperrun'),
        ),
    ]
