# Generated by Django 5.1.4 on 2025-01-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedata',
            name='img_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='img_dir',
            field=models.TextField(blank=True, null=True),
        ),
    ]
