# Generated by Django 5.1.4 on 2025-01-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapedata_img_name_scraperrun_img_dir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapebatch',
            old_name='notes_in_batch',
            new_name='nodes_in_batch',
        ),
        migrations.RenameField(
            model_name='scraperrun',
            old_name='scrape_max_notes',
            new_name='scrape_max_nodes',
        ),
        migrations.RenameField(
            model_name='scraperrun',
            old_name='scrape_notes_per_batch',
            new_name='scrape_nodes_per_batch',
        ),
    ]
