# Generated by Django 5.1.4 on 2025-01-20 13:05

import scraper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_notes_in_batch_scrapebatch_nodes_in_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedata',
            name='img_download_status',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[scraper.models.validate_img_status]),
        ),
    ]
