# Generated by Django 5.1.4 on 2025-02-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_scrapebatch_response_on_error_scraperrun_error_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedata',
            name='extracted_hashtags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
